project:
  type: website
  output-dir: docs

website:
  title: "Anthony J Fitch"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

